<?php

return [
    "module_name" => [
        "single" => "Agenda",
        "multiple" => "Agenda"
    ],
    "fields" => [
        "uploads" => [
            "active" => true,
            "type" => "",
            "title" => "Uploads",
            "read" => false,
            "required" => false,
        ],
        "maps" => [
            "active" => true,
            "type" => "",
            "title" => "Google Maps",
            "read" => false,
            "required" => false,
        ],
        "DIVIDER_1" => [
            "active" => false,
            "type" => "divider",
            "title" => "Basis gegevens",
            "read" => true,
            "required" => false,
        ],
        "title" => [
            "active" => true,
            "type" => "text",
            "title" => "Titel",
            "read" => true,
            "required" => false,
        ],
        "title_2" => [
            "active" => false,
            "type" => "text",
            "title" => "Subtitel",
            "read" => true,
            "required" => false,
        ],
        "from" => [
            "active" => true,
            "type" => "datetime-local",
            "title" => "Van",
            "read" => true,
            "required" => false,
        ],
        "till" => [
            "active" => true,
            "type" => "datetime-local",
            "title" => "Tot",
            "read" => true,
            "required" => false,
        ],
        "show_from" => [
            "active" => true,
            "type" => "datetime-local",
            "title" => "Tonen vanaf",
            "read" => true,
            "required" => false,
        ],
        "show_till" => [
            "active" => true,
            "type" => "datetime-local",
            "title" => "Tonen t/m",
            "read" => true,
            "required" => false,
        ],
        "slug" => [
            "active" => true,
            "type" => "text",
            "title" => "Slug",
            "read" => true,
            "required" => true,
        ],
        "seo_title" => [
            "active" => true,
            "type" => "text",
            "title" => "SEO Titel",
            "read" => true,
            "required" => false,
        ],
        "seo_description" => [
            "active" => true,
            "type" => "textarea",
            "title" => "SEO omschrijving",
            "read" => true,
            "required" => false,
        ],
        "tags" => [
            "active" => false,
            "type" => "text",
            "title" => "Tags",
            "read" => true,
            "required" => false,
        ],
        "summary" => [
            "active" => false,
            "type" => "textarea",
            "title" => "Samenvatting",
            "read" => true,
            "required" => false,
        ],
        "excerpt" => [
            "active" => true,
            "type" => "textarea",
            "title" => "Inleiding",
            "read" => true,
            "required" => false,
        ],
        "content" => [
            "active" => true,
            "type" => "editor",
            "title" => "Bericht",
            "read" => true,
            "required" => false,
        ],
        "DIVIDER_2" => [
            "active" => false,
            "type" => "divider",
            "title" => "Overige gegevens",
            "read" => true,
            "required" => false,
        ],
        "price" => [
            "active" => false,
            "type" => "text",
            "title" => "Prijs",
            "read" => true,
            "required" => false,
        ],
        "currency" => [
            "active" => false,
            "type" => "text",
            "title" => "Valuta",
            "read" => true,
            "required" => false,
        ],
        "organizer_name" => [
            "active" => false,
            "type" => "text",
            "title" => "Organisator",
            "read" => true,
            "required" => false,
        ],
        "organizer_url" => [
            "active" => false,
            "type" => "text",
            "title" => "Organisator url",
            "read" => true,
            "required" => false,
        ],
        "DIVIDER_3" => [
            "active" => false,
            "type" => "divider",
            "title" => "Contact gegevens",
            "read" => true,
            "required" => false,
        ],
        "contact" => [
            "active" => false,
            "type" => "text",
            "title" => "Contactpersoon",
            "read" => true,
            "required" => false,
        ],
        "email" => [
            "active" => false,
            "type" => "text",
            "title" => "Email",
            "read" => true,
            "required" => false,
        ],
        "phone" => [
            "active" => false,
            "type" => "text",
            "title" => "Telefoon",
            "read" => true,
            "required" => false,
        ],
        "address" => [
            "active" => false,
            "type" => "text",
            "title" => "Adres",
            "read" => true,
            "required" => false,
        ],
        "zipcode" => [
            "active" => false,
            "type" => "text",
            "title" => "Postcode",
            "read" => true,
            "required" => false,
        ],
        "city" => [
            "active" => false,
            "type" => "text",
            "title" => "Woonplaats",
            "read" => true,
            "required" => false,
        ],
        "country" => [
            "active" => false,
            "type" => "text",
            "title" => "Land",
            "read" => true,
            "required" => false,
        ],
        "longitude" => [
            "active" => false,
            "type" => "text",
            "title" => "Lengtegraad",
            "read" => true,
            "required" => false,
        ],
        "latitude" => [
            "active" => false,
            "type" => "text",
            "title" => "Breedtegraad",
            "read" => true,
            "required" => false,
        ],
    ]
];
